In [23]:
import numpy as np
import pandas as pd

In [24]:
df=pd.read_csv('/Users/dinesh/Downloads/t20i_info.csv')

In [25]:
df.head()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground

In [26]:
df['batting_team'].value_counts().sort_index()

batting_team
Afghanistan     1475
Australia       6611
Bangladesh      3368
England         6473
India           7746
New Zealand     7994
Pakistan        8355
South Africa    7940
Sri Lanka       7305
West Indies     6621
Name: count, dtype: int64

In [27]:
df['bowling_team'].value_counts()

bowling_team
Australia       8481
England         8038
Pakistan        7878
India           7235
West Indies     7080
New Zealand     6805
Sri Lanka       6731
South Africa    5790
Bangladesh      4893
Afghanistan      957
Name: count, dtype: int64

In [28]:
df['city'].value_counts()>600

city
Colombo           True
Mirpur            True
Johannesburg      True
Auckland          True
Cape Town         True
                 ...
Potchefstroom    False
Dharamsala       False
Ahmedabad        False
Melbourne        False
Sylhet           False
Name: count, Length: 81, dtype: bool

In [29]:
df.tail()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [30]:
df.shape

(63888, 9)

In [31]:
df.isnull().sum()

Unnamed: 0             0
match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                8548
venue                  0
dtype: int64

In [32]:
df.value_counts

<bound method DataFrame.value_counts of        Unnamed: 0  match_id batting_team bowling_team  ball  runs  \
0               0         2    Australia    Sri Lanka   0.1     0
1               1         2    Australia    Sri Lanka   0.2     0
2               2         2    Australia    Sri Lanka   0.3     1
3               3         2    Australia    Sri Lanka   0.4     2
4               4         2    Australia    Sri Lanka   0.5     0
...           ...       ...          ...          ...   ...   ...
63883         121       964    Sri Lanka    Australia  19.3     1
63884         122       964    Sri Lanka    Australia  19.4     0
63885         123       964    Sri Lanka    Australia  19.5     0
63886         124       964    Sri Lanka    Australia  19.6     2
63887         125       964    Sri Lanka    Australia  19.7     1

      player_dismissed     city                     venue
0                    0      NaN  Melbourne Cricket Ground
1                    0      NaN  Melbourne Cricket Ground
2                    0      NaN  Melbourne Cricket Ground
3                    0      NaN  Melbourne Cricket Ground
4                    0      NaN  Melbourne Cricket Ground
...                ...      ...                       ...
63883                0  Colombo       R Premadasa Stadium
63884                0  Colombo       R Premadasa Stadium
63885      DM de Silva  Colombo       R Premadasa Stadium
63886                0  Colombo       R Premadasa Stadium
63887                0  Colombo       R Premadasa Stadium

[63888 rows x 9 columns]>

In [33]:
#cricbuzz,tv,onlineplatforms->cricket score predictor

In [34]:
df[df['city'].isnull()].shape

(8548, 9)

batting team,bowling team,city,current score,balls left,wicket left,current run rate,last five/six->powerplay

In [35]:
df[df['city'].isnull()]

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...,...
63757,118,963,Australia,Sri Lanka,19.2,1,0,NaN,Pallekele International Cricket Stadium
63758,119,963,Australia,Sri Lanka,19.3,4,0,NaN,Pallekele International Cricket Stadium
63759,120,963,Australia,Sri Lanka,19.4,4,0,NaN,Pallekele International Cricket Stadium
63760,121,963,Australia,Sri Lanka,19.5,6,0,NaN,Pallekele International Cricket Stadium
63761,122,963,Australia,Sri Lanka,19.6,0,TM Head,NaN,Pallekele International Cricket Stadium

In [36]:
df[df['city'].isnull()]['venue'][0].split(" ")[0]

'Melbourne'

In [37]:
df['city'] = df['city'].fillna(df['venue'].apply(str.split).str[0])

In [38]:
df.head()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground

In [39]:
df[df['city'].isnull()].shape

(0, 9)

In [40]:
df.isnull().sum()

Unnamed: 0          0
match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [41]:
df['city'].value_counts()

city
Colombo          4086
Mirpur           3420
Johannesburg     3331
Dubai            2969
Auckland         2532
                 ...
Nairobi           123
Potchefstroom     122
Dharamsala        122
Ahmedabad         121
Carrara            64
Name: count, Length: 86, dtype: int64

In [42]:
#cities which are eligible for playing and more number of matches have been played
entitled_cities=df['city'].value_counts()[df['city'].value_counts()>600].index.tolist()

In [43]:
entitled_cities

['Colombo',
 'Mirpur',
 'Johannesburg',
 'Dubai',
 'Auckland',
 'Cape Town',
 'London',
 'Pallekele',
 'Barbados',
 'Sydney',
 'Melbourne',
 'Durban',
 'St Lucia',
 'Wellington',
 'Lauderhill',
 'Hamilton',
 'Centurion',
 'Manchester',
 'Abu Dhabi',
 'Mumbai',
 'Nottingham',
 'Southampton',
 'Mount Maunganui',
 'Chittagong',
 'Kolkata',
 'Lahore',
 'Delhi',
 'Nagpur',
 'Chandigarh',
 'Adelaide',
 'Bangalore',
 'St Kitts',
 'Cardiff',
 'Christchurch',
 'Trinidad']

In [44]:
df['city'].isin(entitled_cities).value_counts()

city
True     50501
False    13387
Name: count, dtype: int64

In [45]:
df=df[df['city'].isin(entitled_cities)]

In [46]:
df.shape

(50501, 9)

In [47]:
df['match_id'].dtypes

dtype('int64')

In [48]:
df.dtypes

Unnamed: 0            int64
match_id              int64
batting_team         object
bowling_team         object
ball                float64
runs                  int64
player_dismissed     object
city                 object
venue                object
dtype: object

In [49]:
print(df['match_id'].apply(type).value_counts())

match_id
<class 'int'>    50501
Name: count, dtype: int64

In [50]:
df.groupby('match_id')['runs'].apply(lambda x: x.cumsum())

match_id
2         0          0
          1          0
          2          1
          3          3
          4          3
                  ...
964       63883    125
          63884    125
          63885    125
          63886    127
          63887    128
Name: runs, Length: 50501, dtype: int64

In [51]:
df['current'] = df.groupby('match_id')['runs'].transform('cumsum')

/var/folders/4x/j8zwk7vj55bg41_cd3c16kyr0000gn/T/ipykernel_45289/893136810.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['current'] = df.groupby('match_id')['runs'].transform('cumsum')

In [52]:
df['current']

0          0
1          0
2          1
3          3
4          3
        ...
63883    125
63884    125
63885    125
63886    127
63887    128
Name: current, Length: 50501, dtype: int64

In [53]:
df

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3
...,...,...,...,...,...,...,...,...,...,...
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,125
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,125
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,125
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,127
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,128

In [54]:
df.head()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3

In [55]:
df['over']=df['ball'].apply(lambda x: str(x).split(".")[0])
df['ball_number']=df['ball'].apply(lambda x: str(x).split(".")[1])

/var/folders/4x/j8zwk7vj55bg41_cd3c16kyr0000gn/T/ipykernel_45289/1356679233.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['over']=df['ball'].apply(lambda x: str(x).split(".")[0])
/var/folders/4x/j8zwk7vj55bg41_cd3c16kyr0000gn/T/ipykernel_45289/1356679233.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ball_number']=df['ball'].apply(lambda x: str(x).split(".")[1])

In [56]:
df.head(30)

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current,over,ball_number
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0,0,1
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0,0,2
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1,0,3
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3,0,4
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3,0,5
5,5,2,Australia,Sri Lanka,0.6,3,0,Melbourne,Melbourne Cricket Ground,6,0,6
6,6,2,Australia,Sri Lanka,1.1,0,0,Melbourne,Melbourne Cricket Ground,6,1,1
7,7,2,Australia,Sri Lanka,1.2,1,0,Melbourne,Melbourne Cricket Ground,7,1,2
8,8,2,Australia,Sri Lanka,1.3,0,0,Melbourne,Melbourne Cricket Ground,7,1,3
9,9,2,Australia,Sri Lanka,1.4,0,0,Melbourne,Melbourne Cricket Ground,7,1,4
10,10,2,Australia,Sri Lanka,1.5,4,0,Melbourne,Melbourne Cricket Ground,11,1,5
11,11,2,Australia,Sri Lanka,1.6,2,0,Melbourne,Melbourne Cricket Ground,13,1,6
12,12,2,Australia,Sri Lanka,2.1,1,0,Melbourne,Melbourne Cricket Ground,14,2,1
13,13,2,Australia,Sri Lanka,2.2,1,0,Melbourne,Melbourne Cricket Ground,15,2,2
14,14,2,Australia,Sri Lanka,2.3,0,0,Melbourne,Melbourne Cricket Ground,15,2,3
15,15,2,Australia,Sri Lanka,2.4,0,0,Melbourne,Melbourne Cricket Ground,15,2,4
16,16,2,Australia,Sri Lanka,2.5,4,0,Melbourne,Melbourne Cricket Ground,19,2,5
17,17,2,Australia,Sri Lanka,2.6,0,0,Melbourne,Melbourne Cricket Ground,19,2,6
18,18,2,Australia,Sri Lanka,3.1,0,0,Melbourne,Melbourne Cricket Ground,19,3,1
19,19,2,Australia,Sri Lanka,3.2,1,0,Melbourne,Melbourne Cricket Ground,20,3,2
20,20,2,Australia,Sri Lanka,3.3,1,0,Melbourne,Melbourne Cricket Ground,21,3,3
21,21,2,Australia,Sri Lanka,3.4,1,0,Melbourne,Melbourne Cricket Ground,22,3,4
22,22,2,Australia,Sri Lanka,3.5,4,0,Melbourne,Melbourne Cricket Ground,26,3,5
23,23,2,Australia,Sri Lanka,3.6,1,0,Melbourne,Melbourne Cricket Ground,27,3,6
24,24,2,Australia,Sri Lanka,4.1,3,0,Melbourne,Melbourne Cricket Ground,30,4,1
25,25,2,Australia,Sri Lanka,4.2,3,0,Melbourne,Melbourne Cricket Ground,33,4,2
26,26,2,Australia,Sri Lanka,4.3,4,0,Melbourne,Melbourne Cricket Ground,37,4,3
27,27,2,Australia,Sri Lanka,4.4,4,0,Melbourne,Melbourne Cricket Ground,41,4,4
28,28,2,Australia,Sri Lanka,4.5,1,0,Melbourne,Melbourne Cricket Ground,42,4,5
29,29,2,Australia,Sri Lanka,4.6,1,0,Melbourne,Melbourne Cricket Ground,43,4,6

In [57]:
df = df.assign(balls_delivered = df['over'].astype(int) * 6 + df['ball_number'].astype(int))

In [58]:
df.tail()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current,over,ball_number,balls_delivered
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,125,19,3,117
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,125,19,4,118
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,125,19,5,119
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,127,19,6,120
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,128,19,7,121

In [59]:
df['no_of_balls_left'] = df['balls_delivered'].apply(lambda x: max(120 - x, 0))

In [60]:
df.tail()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current,over,ball_number,balls_delivered,no_of_balls_left
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,125,19,3,117,3
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,125,19,4,118,2
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,125,19,5,119,1
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,127,19,6,120,0
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,128,19,7,121,0

In [61]:

df['player_dismissed'] = df['player_dismissed'].apply(lambda x: 1 if x != '0' else '0')

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50501 entries, 0 to 63887
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        50501 non-null  int64
 1   match_id          50501 non-null  int64
 2   batting_team      50501 non-null  object
 3   bowling_team      50501 non-null  object
 4   ball              50501 non-null  float64
 5   runs              50501 non-null  int64
 6   player_dismissed  50501 non-null  object
 7   city              50501 non-null  object
 8   venue             50501 non-null  object
 9   current           50501 non-null  int64
 10  over              50501 non-null  object
 11  ball_number       50501 non-null  object
 12  balls_delivered   50501 non-null  int64
 13  no_of_balls_left  50501 non-null  int64
dtypes: float64(1), int64(6), object(7)
memory usage: 5.8+ MB

In [63]:
df['player_dismissed'] = df['player_dismissed'].astype(int)

In [64]:
df

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current,over,ball_number,balls_delivered,no_of_balls_left
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0,0,1,1,119
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0,0,2,2,118
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1,0,3,3,117
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3,0,4,4,116
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium,125,19,3,117,3
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium,125,19,4,118,2
63885,123,964,Sri Lanka,Australia,19.5,0,1,Colombo,R Premadasa Stadium,125,19,5,119,1
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium,127,19,6,120,0
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium,128,19,7,121,0

In [65]:
df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()

In [66]:
df['wickets_left'] = df['player_dismissed'].apply(lambda x: 10 - x)

In [67]:
df.tail()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current,over,ball_number,balls_delivered,no_of_balls_left,wickets_left
63883,121,964,Sri Lanka,Australia,19.3,1,8,Colombo,R Premadasa Stadium,125,19,3,117,3,2
63884,122,964,Sri Lanka,Australia,19.4,0,8,Colombo,R Premadasa Stadium,125,19,4,118,2,2
63885,123,964,Sri Lanka,Australia,19.5,0,9,Colombo,R Premadasa Stadium,125,19,5,119,1,1
63886,124,964,Sri Lanka,Australia,19.6,2,9,Colombo,R Premadasa Stadium,127,19,6,120,0,1
63887,125,964,Sri Lanka,Australia,19.7,1,9,Colombo,R Premadasa Stadium,128,19,7,121,0,1

In [68]:
df['current_run_rate']=(df['current']*6)/df['balls_delivered']

In [69]:
df.tail()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current,over,ball_number,balls_delivered,no_of_balls_left,wickets_left,current_run_rate
63883,121,964,Sri Lanka,Australia,19.3,1,8,Colombo,R Premadasa Stadium,125,19,3,117,3,2,6.410256
63884,122,964,Sri Lanka,Australia,19.4,0,8,Colombo,R Premadasa Stadium,125,19,4,118,2,2,6.355932
63885,123,964,Sri Lanka,Australia,19.5,0,9,Colombo,R Premadasa Stadium,125,19,5,119,1,1,6.302521
63886,124,964,Sri Lanka,Australia,19.6,2,9,Colombo,R Premadasa Stadium,127,19,6,120,0,1,6.350000
63887,125,964,Sri Lanka,Australia,19.7,1,9,Colombo,R Premadasa Stadium,128,19,7,121,0,1,6.347107

In [70]:
groups = df.groupby('match_id')
match_ids = df['match_id'].unique()
last_five = []

df['last_30_runs'] = df.groupby('match_id')['runs'].transform(lambda x: x.rolling(window=30).sum())

In [96]:
# 8. Adding batting team strength based on past performance (mean runs in past matches)
df['batting_team_strength'] = df.groupby('batting_team')['runs'].transform('mean')

# 9. Adding bowling team strength (mean wickets taken in past matches)
df['bowling_team_strength'] = df.groupby('bowling_team')['runs'].transform('mean')
# 10. Adding venue impact (average runs scored in past matches at the same venue)
df['venue_avg_runs'] = df.groupby('venue')['runs'].transform('mean')

# 11. Batting impact (difference between team performance and venue average)
df['batting_impact'] = df['current'] - df['venue_avg_runs']
 #13. Adding match_id-specific features
df['match_venue'] = df['match_id'].astype(str) + '_' + df['venue']

# 15. Bowling team wickets in last 5 overs
df['bowling_team_last_5_wickets'] = df.groupby('bowling_team')['player_dismissed'].transform(lambda x: x.rolling(window=30).sum())

# Feature that combines the runs and wickets left for the team
df['runs_wickets_left_ratio'] = df['runs'] / (df['wickets_left'] + 1)  # Avoid division by zero

In [97]:
df

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue,current,...,wickets_left,current_run_rate,last_30_runs,batting_team_strength,bowling_team_strength,venue_avg_runs,batting_impact,match_venue,bowling_team_last_5_wickets,runs_wickets_left_ratio
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,0,...,10,0.000000,NaN,1.367884,1.302055,1.153748,-1.153748,2_Melbourne Cricket Ground,NaN,0.000000
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,0,...,10,0.000000,NaN,1.367884,1.302055,1.153748,-1.153748,2_Melbourne Cricket Ground,NaN,0.000000
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,1,...,10,2.000000,NaN,1.367884,1.302055,1.153748,-0.153748,2_Melbourne Cricket Ground,NaN,0.090909
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,3,...,10,4.500000,NaN,1.367884,1.302055,1.153748,1.846252,2_Melbourne Cricket Ground,NaN,0.181818
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,3,...,10,3.600000,NaN,1.367884,1.302055,1.153748,1.846252,2_Melbourne Cricket Ground,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63883,121,964,Sri Lanka,Australia,19.3,1,8,Colombo,R Premadasa Stadium,125,...,2,6.410256,32.0,1.271629,1.255141,1.267851,123.732149,964_R Premadasa Stadium,222.0,0.333333
63884,122,964,Sri Lanka,Australia,19.4,0,8,Colombo,R Premadasa Stadium,125,...,2,6.355932,32.0,1.271629,1.255141,1.267851,123.732149,964_R Premadasa Stadium,223.0,0.000000
63885,123,964,Sri Lanka,Australia,19.5,0,9,Colombo,R Premadasa Stadium,125,...,1,6.302521,32.0,1.271629,1.255141,1.267851,123.732149,964_R Premadasa Stadium,225.0,0.000000
63886,124,964,Sri Lanka,Australia,19.6,2,9,Colombo,R Premadasa Stadium,127,...,1,6.350000,33.0,1.271629,1.255141,1.267851,125.732149,964_R Premadasa Stadium,227.0,1.000000
63887,125,964,Sri Lanka,Australia,19.7,1,9,Colombo,R Premadasa Stadium,128,...,1,6.347107,32.0,1.271629,1.255141,1.267851,126.732149,964_R Premadasa Stadium,229.0,0.500000

In [95]:
df['batting_team_strength'].value_counts()

batting_team_strength
1.334621    7250
1.254300    6744
1.271629    6207
1.359922    6143
1.339652    5697
1.367884    5393
1.245847    5056
1.321512    4681
1.171012    2608
0.995845     722
Name: count, dtype: int64

In [112]:
final_df=df.groupby('match_id').sum()['runs'].reset_index().merge(df,on='match_id')

In [113]:
final_df

,match_id,runs_x,Unnamed: 0,batting_team,bowling_team,ball,runs_y,player_dismissed,city,venue,...,wickets_left,current_run_rate,last_30_runs,batting_team_strength,bowling_team_strength,venue_avg_runs,batting_impact,match_venue,bowling_team_last_5_wickets,runs_wickets_left_ratio
0,2,168,0,Australia,Sri Lanka,0.1,0,0,Melbourne,Melbourne Cricket Ground,...,10,0.000000,NaN,1.367884,1.302055,1.153748,-1.153748,2_Melbourne Cricket Ground,NaN,0.000000
1,2,168,1,Australia,Sri Lanka,0.2,0,0,Melbourne,Melbourne Cricket Ground,...,10,0.000000,NaN,1.367884,1.302055,1.153748,-1.153748,2_Melbourne Cricket Ground,NaN,0.000000
2,2,168,2,Australia,Sri Lanka,0.3,1,0,Melbourne,Melbourne Cricket Ground,...,10,2.000000,NaN,1.367884,1.302055,1.153748,-0.153748,2_Melbourne Cricket Ground,NaN,0.090909
3,2,168,3,Australia,Sri Lanka,0.4,2,0,Melbourne,Melbourne Cricket Ground,...,10,4.500000,NaN,1.367884,1.302055,1.153748,1.846252,2_Melbourne Cricket Ground,NaN,0.181818
4,2,168,4,Australia,Sri Lanka,0.5,0,0,Melbourne,Melbourne Cricket Ground,...,10,3.600000,NaN,1.367884,1.302055,1.153748,1.846252,2_Melbourne Cricket Ground,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50496,964,128,121,Sri Lanka,Australia,19.3,1,8,Colombo,R Premadasa Stadium,...,2,6.410256,32.0,1.271629,1.255141,1.267851,123.732149,964_R Premadasa Stadium,222.0,0.333333
50497,964,128,122,Sri Lanka,Australia,19.4,0,8,Colombo,R Premadasa Stadium,...,2,6.355932,32.0,1.271629,1.255141,1.267851,123.732149,964_R Premadasa Stadium,223.0,0.000000
50498,964,128,123,Sri Lanka,Australia,19.5,0,9,Colombo,R Premadasa Stadium,...,1,6.302521,32.0,1.271629,1.255141,1.267851,123.732149,964_R Premadasa Stadium,225.0,0.000000
50499,964,128,124,Sri Lanka,Australia,19.6,2,9,Colombo,R Premadasa Stadium,...,1,6.350000,33.0,1.271629,1.255141,1.267851,125.732149,964_R Premadasa Stadium,227.0,1.000000
50500,964,128,125,Sri Lanka,Australia,19.7,1,9,Colombo,R Premadasa Stadium,...,1,6.347107,32.0,1.271629,1.255141,1.267851,126.732149,964_R Premadasa Stadium,229.0,0.500000

In [114]:
final_df.columns

Index(['match_id', 'runs_x', 'Unnamed: 0', 'batting_team', 'bowling_team',
       'ball', 'runs_y', 'player_dismissed', 'city', 'venue', 'current',
       'over', 'ball_number', 'balls_delivered', 'no_of_balls_left',
       'wickets_left', 'current_run_rate', 'last_30_runs',
       'batting_team_strength', 'bowling_team_strength', 'venue_avg_runs',
       'batting_impact', 'match_venue', 'bowling_team_last_5_wickets',
       'runs_wickets_left_ratio'],
      dtype='object')

In [116]:
final_df = final_df[['batting_team', 'bowling_team', 'city', 'current', 'no_of_balls_left', 'wickets_left', 
                      'current_run_rate', 'last_30_runs', 'batting_team_strength', 'bowling_team_strength', 
                      'venue_avg_runs', 'batting_impact', 'runs_x']]

In [118]:
final_df.dropna(inplace=True)

/var/folders/4x/j8zwk7vj55bg41_cd3c16kyr0000gn/T/ipykernel_45289/2709626079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace=True)

In [119]:
final_df.isnull().sum()

batting_team             0
bowling_team             0
city                     0
current                  0
no_of_balls_left         0
wickets_left             0
current_run_rate         0
last_30_runs             0
batting_team_strength    0
bowling_team_strength    0
venue_avg_runs           0
batting_impact           0
runs_x                   0
dtype: int64

In [120]:
final_df.shape

(38477, 13)

In [121]:
final_df=final_df.sample(final_df.shape[0])

In [122]:
final_df.shape

(38477, 13)

In [123]:
X=final_df.drop(columns=['runs_x'])
y=final_df['runs_x']

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [85]:

X_train

,batting_team,bowling_team,city,current,no_of_balls_left,wickets_left,current_run_rate,last_30_runs
42682,England,Australia,Cardiff,136,29,8,8.967033,70.0
26159,Pakistan,Australia,St Lucia,111,38,8,8.121951,30.0
43740,New Zealand,South Africa,Durban,61,81,10,9.384615,56.0
18487,New Zealand,South Africa,Johannesburg,101,15,3,5.771429,23.0
23031,Bangladesh,West Indies,St Kitts,50,75,6,6.666667,38.0
...,...,...,...,...,...,...,...,...
28577,Pakistan,New Zealand,Christchurch,90,57,8,8.571429,30.0
13412,West Indies,New Zealand,Auckland,179,22,3,10.959184,49.0
28797,Pakistan,South Africa,Abu Dhabi,39,87,8,7.090909,25.0
2030,New Zealand,England,Wellington,56,77,9,7.813953,34.0
36108,Australia,Pakistan,Dubai,88,5,1,4.591304,20.0

In [86]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [87]:
transformer = ColumnTransformer(transformers=[('transformer', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])],remainder='passthrough')

In [88]:
pipe=Pipeline(steps=[
    ('step1',transformer),
    ('step2',StandardScaler()),
    ('step3',XGBRegressor(n_estimators=1000,learning_rate=0.2,max_depth=12,random_state=1))
])

In [89]:
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)

In [126]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from catboost import CatBoostRegressor
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.impute import SimpleImputer
import pandas as pd

transformer = ColumnTransformer(
    transformers=[('transformer', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])],
    remainder='passthrough'
)

# Defining models for testing
models = {
    'XGBoost': XGBRegressor(n_estimators=1000, learning_rate=0.2, max_depth=12, random_state=1),
    'Random Forest': RandomForestRegressor(n_estimators=1000, random_state=1),
    'CatBoost': CatBoostRegressor(iterations=1000, depth=10, learning_rate=0.1, random_seed=1, silent=True),
    'Linear Regression': LinearRegression(),
    'Lasso Regression': Lasso(alpha=0.1)
}

# Pipeline setup with ColumnTransformer and models
for model_name, model in models.items():
    print(f"Training {model_name}...")
    
    pipe = Pipeline(steps=[
        ('step1', transformer),
        ('step2', SimpleImputer(strategy='mean')),  # Handle missing values
        ('step3', StandardScaler()),
        ('step4', model)
    ])
    
    # Fitting the model
    pipe.fit(X_train, y_train)
    
    # Making predictions
    y_pred = pipe.predict(X_test)
    
    # Evaluating the model
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    
    print(f"{model_name} - R2 Score: {r2}")
    print(f"{model_name} - Mean Absolute Error: {mae}\n")

Training XGBoost...
XGBoost - R2 Score: 0.9871749849960721
XGBoost - Mean Absolute Error: 1.630248457379252

Training Random Forest...
Random Forest - R2 Score: 0.9792691964887846
Random Forest - Mean Absolute Error: 2.055116266489704

Training CatBoost...
CatBoost - R2 Score: 0.9866492649187664
CatBoost - Mean Absolute Error: 2.114666694264175

Training Linear Regression...
Linear Regression - R2 Score: 0.7017509928021047
Linear Regression - Mean Absolute Error: 12.949267375770054

Training Lasso Regression...
Lasso Regression - R2 Score: 0.6993213886177793
Lasso Regression - Mean Absolute Error: 12.963274961579657

In [127]:
r2_score(y_test,y_pred)

0.6993213886177793

In [128]:
mean_absolute_error(y_test,y_pred)

12.963274961579657

In [129]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))